Merge pull request #151 in MML/infobip-mobile-messaging-android from tjuric-MM-2841-Bugfix-MobileMessagingJobService to master
Squashed commit of the following:

commit bfbf1842d39a2f2558704ca69142bb7b6585cc2d
Author: tjuric <tereza.juric@infobip.com>
Date:   Wed Aug 15 08:28:40 2018 +0200

    MM-2841 - Bugfix - NoClassDefFoundError for MobileMessagingJobService on 4.4.2